// src/lib/products.js
export const products = [
  {
    id: 1,
    name: "Starter",
    tier: "Free tier",
    price: 0,
    oldPrice: null,
    desc: "Perfect for individuals just getting started.",
    badge: "New",
    popular: false,
    iconColor: "#EEEDFE",
    iconStroke: "#534AB7",
  },
  {
    id: 2,
    name: "Basic",
    tier: "Essential tier",
    price: 199,
    oldPrice: 299,
    desc: "Core tools for small teams and solo creators.",
    badge: "Sale",
    popular: false,
    iconColor: "#E1F5EE",
    iconStroke: "#0F6E56",
  },
  {
    id: 3,
    name: "Pro",
    tier: "Growth tier",
    price: 499,
    oldPrice: null,
    desc: "Advanced features for growing businesses.",
    badge: "Popular",
    popular: true,
    iconColor: "#E6F1FB",
    iconStroke: "#185FA5",
  },
  {
    id: 4,
    name: "Turbo",
    tier: "Power tier",
    price: 799,
    oldPrice: 999,
    desc: "Blazing speed and priority processing.",
    badge: "Sale",
    popular: false,
    iconColor: "#FAEEDA",
    iconStroke: "#854F0B",
  },
  {
    id: 5,
    name: "Team",
    tier: "Collaboration tier",
    price: 1299,
    oldPrice: null,
    desc: "Shared workspaces and role management.",
    badge: null,
    popular: false,
    iconColor: "#FAECE7",
    iconStroke: "#993C1D",
  },
  {
    id: 6,
    name: "Enterprise",
    tier: "Custom tier",
    price: null,
    oldPrice: null,
    desc: "Dedicated support, SLA, and custom pricing.",
    badge: null,
    popular: false,
    iconColor: "#F1EFE8",
    iconStroke: "#444441",
  },
];
